-- Scenario 2 Requirement : Insert an audit record whenever a transaction is inserted.

CREATE TABLE AuditLog
(
    AuditID NUMBER GENERATED BY DEFAULT AS IDENTITY,
    TransactionID NUMBER,
    ActionDate DATE,
    ActionType VARCHAR2(50)
);

CREATE OR REPLACE TRIGGER LogTransaction
AFTER INSERT
ON Transactions
FOR EACH ROW
BEGIN

    INSERT INTO AuditLog
    (
        TransactionID,
        ActionDate,
        ActionType
    )
    VALUES
    (
        :NEW.TransactionID,
        SYSDATE,
        'INSERT'
    );

END;
/

-- Test 
INSERT INTO Transactions
(
    TransactionID,
    AccountID,
    TransactionDate,
    Amount,
    TransactionType
)
VALUES
(
    3,
    1,
    SYSDATE,
    100,
    'Deposit'
);

--Verify
SELECT *
FROM AuditLog;
/* Output
Table AUDITLOG created.
Elapsed: 00:00:00.022
Trigger LOGTRANSACTION compiled
Elapsed: 00:00:00.027
1 row inserted.
Elapsed: 00:00:00.015
    | AUDITID | TRANSACTIONID | ACTIONDATE            | ACTIONTYPE   |
----------------------------------------------------------------------
  1 |       1 |  3            | 6/17/2026, 4:5`:05 PM | INSERT       |
----------------------------------------------------------------------
*/